
#include "gtest/gtest.h"

#include "CommandTest.h"
#include "VertexTest.h"
#include "StoneTest.h"
#include "MoveTest.h"

#include "ProtocolVersionCommandTest.h"
#include "NameCommandTest.h"
#include "VersionCommandTest.h"
#include "BoardSizeCommandTest.h"
#include "ClearBoardCommandTest.h"
#include "KomiCommandTest.h"
#include "FixedHandicapCommandTest.h"
#include "PlaceFreeHandicapCommandTest.h"
#include "SetFreeHandicapCommandTest.h"
#include "KnownCommandCommandTest.h"
#include "ListCommandsCommandTest.h"
#include "PlayCommandTest.h"
#include "QuitCommandTest.h"
#include "GenMoveCommandTest.h"
#include "UndoCommandTest.h"
#include "TimeSettingsCommandTest.h"
#include "TimeLeftCommandTest.h"
#include "FinalScoreCommandTest.h"
#include "FinalStatusListCommandTest.h"
#include "LoadSgfCommandTest.h"
#include "RegGenMoveCommandTest.h"
#include "ShowBoardCommandTest.h"
